// These pages appear at the very top of the page
primaryPages = {
  siteSpecific: {
    name: "Site Specific: Photography Exhibitions From Around the World",
    author: "Matt Dunne",
    company: "Tall Poppy Press",
    field: "Book",
    year: 2023,
    text: "A book about photography and how it can be exhibited",
    link: "https://www.tallpoppypress.xyz/product/site-specific-photography-exhibitions-from-around-the-world",
    image: "./index_images/sitespecific.jpg",
    type: "photography",
  },
  rfid: {
    name: "RFID Reader Software",
    author: null,
    company: "CognIoT",
    field: "Software",
    year: 2023,
    text: "Developing prototype software for the PirFlx2.0 RFID Reader Board",
    link: "https://www.youtube.com/watch?v=z8FjJ5C5CEw",
    image: "./index_images/rfid.jpg",
    type: "programming",
  },
  rensou: {
    name: "<moji class='bold'>連想漢字蝶番</moji>",
    author: null,
    company: null,
    field: "App",
    year: 2022,
    text: "Learn kanji by linking their components e.g. <moji>[虫虹工紅、寸吋囗吐土]</moji>",
    link: "https://callumbeaney.github.io/rensou-kanji-hinge/",
    image: "./index_images/rensou.jpg",
    type: "programming",
  },
  c4: {
    name: "C4 Journal",
    author: "Eugenie Shinkle",
    company: null,
    field: "Photography Website",
    year: 2019,
    text: "An online platform where I and a team of writers explore what makes books of photographs special",
    link: "https://www.c4journal.com/",
    image: "./index_images/c4.jpg",
    type: "writing",
  },
  hanzipair: {
    name: "Hanzi Pairing Game",
    author: null,
    company: null,
    field: "Software",
    year: 2023,
    text: "A little game where you have to figure out which hanzi go with which to form a word",
    link: "https://callumbeaney.github.io/chinese-wordsearch-game/",
    image: "./index_images/hanzipair.jpg",
    type: "programming",
  },

}

secondaryPages = {
  prototype: {
    name: "The Prototype",
    author: "Eugenie Shinkle",
    company: "Folium Publishing",
    field: "Photobook",
    year: 2022,
    text: "A collage book inspired by industrial music & building materials",
    link: "https://www.folium.site/shop/p/theprototype",
    image: "./index_images/prototype.jpg",
    type: "photography",
  },
  people: {
    name: "people",
    author: null,
    company: null,
    field: "Software",
    year: 2023,
    text: "A CLI tool for tracking the number of days since you have made contact with people.",
    link: "https://github.com/CallumBeaney/people/",
    image: "./index_images/people.jpg",
    type: "programming",
  },

  baking: {
    name: "Gode Messes",
    author: "Samuel Pegge",
    company: null,
    field: "Baking",
    year: 2022,
    text: "Ich haue stodied for to make þese messes from þ boke The Forme of Cury (c. 1390)",
    link: "./pages/baking/baking.html",
    image: "./index_images/pie.jpg",
    type: "miscellaneous",
  },

  snow: {
    name: "Snow",
    author: "Wesley Stringer",
    company: null,
    field: "Photography",
    year: 2022,
    text: "A portfolio of photographs I made of snow",
    link: "./pages/snow/snow.html",
    image: "./index_images/snow.jpg",
    type: "photography",
  },

  mathConverter: {
    name: "English → Symbolic",
    author: null,
    company: null,
    field: "Webapp",
    year: 2022,
    text: "LaTeX-free logic conversion e.g. [all var in dd goe pi] → [∀𝑥 ∈ 𝔻 ≥ π ]",
    link: "https://callumbeaney.github.io/Symbolic-Notation-Converter/",
    image: "./index_images/symbolic.jpg",
    type: "programming",
  },
  
  kanjipair: {
    name: "Kanji Pairing Game",
    author: null,
    company: null,
    field: "Software",
    year: "2023",
    text: "A Japanese version of my Hanzi game",
    link: "https://callumbeaney.github.io/kanji-pair-game/",
    image: "./index_images/kanjipair.jpg",
    type: "programming",
  },
  

}

tertiaryPages = {
  // aiai: {
  //   name: "<moji class='bold'>爱愛</moji>",
  //   author: null,
  //   company: "Catfish Books",
  //   field: "Photo Zine",
  //   year: 2019,
  //   text: "",
  //   link: "./pages/aiai/aiai.html",
  //   image: "./index_images/aiai.jpg",
  //   type: "photography",
  // },
  
  pink: {
    name: "<moji style='font-size:0.95rem;'>_DSC3071.jpg</moji>",
    author: null,
    company: null,
    field: "Photography?",
    year: 2018,
    text: "This is a photograph that was made without using light",
    link: "./pages/pink/pink.html",
    image: "./index_images/pink.jpg",
    type: "photography",
  },

  singlesurface: {
    name: "Single Surface",
    author: "Eugenie Shinkle, Koji Kitagawa & Eva Louisa Jonas",
    company: "Offshoot Gallery, London",
    field: "Exhibition",
    year: 2021,
    text: "A show I arranged, installed, co-curated, and participated in",
    link: "./pages/singlesurface/singlesurface.html",
    image: "./index_images/singlesurface.jpg",
    type: "photography",
  },

  tsib: {
    name: "The Space In Between",
    author: null,
    company: null,
    field: "Photobook",
    year: 2018,
    text: "Unpublished book dummy. Hand-bound 6m-long accordion book of photographs made around the forest.",
    link: "https://www.youtube.com/watch?v=hY5ldAtOvMQ&feature=youtu.be",
    image: "./index_images/tsib.jpg",
    type: "photography",
  },

  autumnWinter: {
    name: "Autumn/Winter Passing",
    author: null,
    company: "Phases Magazine",
    field: "Photography",
    year: 2018,
    text: "A series of photographs",
    link: "https://www.phasesmag.com/callum-beaney/autumn-winter-passing/",
    image: "./index_images/bird.jpg",
    type: "photography",
  },

  wenyan: {
    name: "<moji class='bold'>公制到市制測量換器</moji>",
    author: null,
    company: null,
    field: "programming",
    year: 2021,
    text: "Converts Metric units to that of the ShiZhi <moji>市制</moji> System as per 1915 regulations",
    link: "https://github.com/CallumBeaney/WenYan-Experiments/blob/main/02.%20Metric%20to%20ShiZhi%20Converter.md",
    image: "./index_images/wenyan.jpg",
    type: "programming",
  },
  
  kearton: {
    name: "On the Keartons and Historical Representations of Nature",
    author: null,
    company: null,
    field: "Article",
    year: 2021,
    text: "Article on nature photography's origins and politics, written for an exhibition catalogue",
    link: "https://c4journal.com/matcaxc4-10-keartons/",
    image: "./index_images/keartonbook.jpg",
    type: "photography",
  },

  nottsExhibition: {
    name: "Day & Night",
    author: null,
    company: "Lakeside Arts Nottingham",
    field: "Exhibition",
    year: 2018,
    text: "Two forest projects shown as part of Genesis Imaging bursary award",
    link: "./pages/nottsexhibition/dayNight.html",
    image: "./index_images/notts.jpg",
    type: "photography",
  },

  rgbbmp: {
    name: "RGB BMP Converter",
    author: null,
    company: null,
    field: "Software",
    year: 2021,
    text: "Simple colourisation CLI tool written in C",
    link: "https://github.com/CallumBeaney/BMP-RGB-filter",
    image: "./index_images/bmp.jpg",
    type: "programming",
  },
  
  smilesgermany: {
    name: "Billboard",
    author: null,
    company: "Studio Othertypes",
    field: "Exhibition",
    year: 2020,
    text: "Advertisements reworked into a poster, put up in Germany",
    link: "./pages/smilesgermany/smilesgermany.html",
    image: "./index_images/smilesgermany.jpg",
    type: "programming",
  },

  somemoments: {
    name: "Some Moments",
    author: null,
    company: null,
    field: "Photography",
    year: 2017,
    text: "Hand-bound book of darkroom prints. I made 5 and gave them to good friends.",
    link: "./pages/somemoments/somemoments.html",
    image: "./index_images/somemoments.jpg",
    type: "photography",
  },
  
  linkedinify: {
    name: "Linkedin-ify",
    author: null,
    company: null,
    field: "Bookmarklet",
    year: 2022,
    text: "An infantile bookmark script (adds extra <moji>\\n</moji> for easier reading)",
    link: "https://callumbeaney.github.io/linkedinify/",
    image: "https://github.com/CallumBeaney/linkedinify/blob/master/linkedin-clone-main/assets/images/header.jpeg?raw=true",
    type: "programming",
  },
  
  injection: {
    name: "Translation of Sakunosuke Oda's 'Injection'",
    author: null,
    company: null,
    field: "Japanese",
    year: 2020,
    text: "This is a short story about trauma by modernist writer Sakunosuke Oda (<moji>織田作之助</moji>, 1913 - 1947)",
    link: "./pages/chuusha/chuusha.html",
    image: "./index_images/chuusha.jpg",
    type: "writing",
  },
  
  lake: {
    name: "'The Prototype' at Lake",
    author: "Eugenie Shinkle",
    company: "Folium",
    field: "Exhibition",
    year: 2023,
    text: "A team-built picture/noise installation",
    link: "./pages/lake/lake.html",
    image: "./index_images/lake.jpg",
    type: "photography",
  },
  
}

// These pages appear at the very end of the page
endPages = {
  matca: {
    name: "Conversations Around Photography, Vietnam & UK",
    author: "Matca",
    company: "British Council Vietnam",
    field: "Editorial",
    year: 2021,
    text: "A series of articles exploring photography",
    link: "https://c4journal.com/matca-c4journal/",
    image: "./index_images/matca.jpg",
    type: "writing",
  },
  dcu: {
    name: "Cultural Heritage Work",
    author: null,
    company: "Digital Content Unit, Cambridge Univeristy Library",
    field: "Photography",
    year: "2018-2019",
    text: "A summary of my work in archives",
    link: "./pages/dcu/dcu.html",
    image: "./index_images/dcu.jpg",
    type: "photography",
  },
  
  drone: {
    name: "Drone Music Fan Club",
    author: null,
    company: null,
    field: "Music",
    year: "2013-2017",
    text: "An old blog I used to do about drone-based music",
    link: "https://dronemusicfanclub.tumblr.com",
    image: "./index_images/drone.jpg",
    type: "music",
  },
  
}
